version: '3.8'

services:
  thefrontend:
    build: ./thefrontend
    ports:
      - "80:80"
    depends_on:
      - thebackend

  thebackend:
    build: ./thebackend
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/springjwt
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=userpassword
    depends_on:
      - mysql
    networks:
      - app-network
    entrypoint: ["./wait-for-it.sh", "mysql:3306", "--", "java", "-jar", "/app.jar"]  # Ensure MySQL is ready

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: springjwt
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    ports:
      - "3306:3306"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
